version: '3.8'

services:
  opendify:
    build: .
    ports:
      - "5000:5000"
    environment:
      # 服务器配置
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
      - ENVIRONMENT=production
      
      # Gunicorn 配置
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # Dify API配置（需要在生产环境中设置）
      - DIFY_API_BASE=${DIFY_API_BASE}
      - MODEL_CONFIG=${MODEL_CONFIG}
    
    # 数据卷挂载
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # 重启策略
    restart: unless-stopped
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
